version: '3.7'

services:

  nginx:
    image: ghcr.io/husky-dev/kremen-api/nginx:latest
    container_name: nginx
    hostname: nginx
    depends_on:
      - main-web
      - transport-web
      - transport-api
      - equipment-web
      - equipment-api
      - cinemas-api
      - watchman
    volumes:
      - 'ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  main-web:
    image: ghcr.io/husky-dev/kremen-main-web/app:latest
    container_name: main-web
    hostname: main-web
    restart: always

  watchman:
    image: ghcr.io/husky-dev/kremen-api/watchman:latest
    container_name: watchman
    hostname: watchman
    depends_on:
      - transport-api
      - equipment-api
      - mongo
      - redis
    environment:
      - NODE_ENV=prd
      - LOG_LEVEL=info
      - SENTRY_DSN=$WATCHMAN_API_SENTRY_DSN
    restart: always

  transport-web:
    image: ghcr.io/husky-dev/kremen-transport-web/app:latest
    container_name: transport-web
    hostname: transport-web
    restart: always

  transport-api:
    image: ghcr.io/husky-dev/kremen-api/transport-api:latest
    container_name: transport-api
    hostname: transport-api
    environment:
      - NODE_ENV=prd
      - LOG_LEVEL=info
      - SENTRY_DSN=$TRANSPORT_API_SENTRY_DSN
    restart: always

  equipment-web:
    image: ghcr.io/husky-dev/kremen-equipment-web/app:latest
    container_name: equipment-web
    hostname: equipment-web
    restart: always

  equipment-api:
    image: ghcr.io/husky-dev/kremen-api/equipment-api:latest
    container_name: equipment-api
    hostname: equipment-api
    environment:
      - NODE_ENV=prd
      - LOG_LEVEL=info
      - SENTRY_DSN=$EQUIPMENT_API_SENTRY_DSN
    restart: always

  cinemas-api:
    image: ghcr.io/husky-dev/kremen-api/cinemas-api:latest
    container_name: cinemas-api
    hostname: cinemas-api
    environment:
      - NODE_ENV=prd
      - LOG_LEVEL=info
      - SENTRY_DSN=$CINEMAS_API_SENTRY_DSN
    restart: always

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  ssl:
    name: ssl
  redis:
    name: redis
  mongo:
    name: mongo
