version: '3.7'

services:

  entry:
    image: ghcr.io/husky-dev/kremen-api/entry:latest
    container_name: entry
    hostname: entry
    depends_on:
      - main-web
      - transport-web
      - transport-api
      - equipment-web
      - equipment-api
      - api
      - watchman
    volumes:
      - 'ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  main-web:
    image: ghcr.io/husky-dev/kremen-main-web/app:latest
    container_name: main-web
    hostname: main-web

  transport-web:
    image: ghcr.io/husky-dev/kremen-transport-web/app:latest
    container_name: transport-web
    hostname: transport-web

  transport-api:
    image: ghcr.io/husky-dev/kremen-api/transport-api:latest
    container_name: transport-api
    hostname: transport-api

  equipment-web:
    image: ghcr.io/husky-dev/kremen-equipment-web/app:latest
    container_name: equipment-web
    hostname: equipment-web

  equipment-api:
    image: ghcr.io/husky-dev/kremen-api/equipment-api:latest
    container_name: equipment-api
    hostname: equipment-api

  watchman:
    image: ghcr.io/husky-dev/kremen-api/watchman:latest
    container_name: watchman
    hostname: watchman
    depends_on:
      - api
      - mongo
      - redis
    restart: always

  api:
    image: ghcr.io/husky-dev/kremen-api/api:latest
    container_name: api
    hostname: api
    depends_on: 
      - redis
    restart: always

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  ssl:
    name: ssl
  redis:
    name: redis
  mongo:
    name: mongo
