version: '3.7'

services:
  web-transport:
    build:
      context: ./web/transport
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app
    volumes:
      - './web/transport:/usr/src/app'
    environment:
      PORT: 6001
    command: 'yarn start:dev'
    ports:
      - '6001:6001'

  web-deputies:
    build:
      context: ./web/deputies
      dockerfile: Dockerfile.dev
    volumes:
      - './web/deputies:/usr/src/app'
    environment:
      PORT: 6002
    command: 'yarn start:dev'
    ports:
      - '6002:6002'

  web-equipment:
    build:
      context: ./web/equipment
      dockerfile: Dockerfile.dev
    volumes:
      - './web/equipment:/usr/src/app'
    environment:
      PORT: 6003
    command: 'yarn start:dev'
    ports:
      - '6003:6003'

  api:
    build:
      context: ./web/equipment
      dockerfile: Dockerfile.dev
    hostname: api
    depends_on: 
      - redis
    volumes:
      - './services/api:/usr/src/app'
    environment:
      PORT: 8080
    command: 'yarn start:dev'
    ports:
      - '8080:8080'

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile.build
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data

volumes:
  redis:
    name: redis