version: '3.7'

services:

  entry:
    build:
      context: ./services/entry
    container_name: entry
    hostname: entry
    depends_on:
      - transport-api
      - equipment-api
      - watchman
      - redis
    volumes:
      - ./services/entry/conf/development:/etc/nginx/conf.d
    ports:
      - '80:80'

  transport-api:
    image: node:14-alpine3.10
    container_name: transport-api
    hostname: transport-api
    working_dir: '/usr/src/app'
    volumes:
      - './services/transport:/usr/src/app'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=trace
      - SENTRY_DSN=$TRANSPORT_API_SENTRY_DSN
    ports:
      - '8081:8080'
    command: 'yarn start:dev'

  equipment-api:
    image: node:14-alpine3.10
    container_name: equipment-api
    hostname: equipment-api
    working_dir: '/usr/src/app'
    volumes:
      - './services/equipment:/usr/src/app'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - SENTRY_DSN=$EQUIPMENT_API_SENTRY_DSN
    ports:
      - '8082:8080'
    command: 'yarn start:dev'

  watchman:
    image: node:14-alpine3.10
    container_name: watchman
    hostname: watchman
    working_dir: '/usr/src/app'
    volumes:
      - './services/watchman:/usr/src/app'
    depends_on:
      - transport-api
      - equipment-api
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - SENTRY_DSN=$WATCHMAN_API_SENTRY_DSN
    command: 'yarn start:dev'

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  redis:
    name: redis
  mongo:
    name: mongo
