version: "3.7"

services:
  web-transport:
    build:
      context: ./web/transport
      dockerfile: Dockerfile.dev
    container_name: kremen-web-transport
    hostname: web-transport
    working_dir: /usr/src/app
    volumes:
      - "./web/transport:/usr/src/app"
    command: "yarn start"
    ports:
      - "8091:8080"

  api:
    image: node:14-alpine3.10
    container_name: kremen-api
    hostname: api
    working_dir: /usr/src/app
    volumes:
      - "./services/api:/usr/src/app"
    environment:
      PORT: 8090
    command: "yarn start:dev"
    ports:
      - "8090:8090"

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile.build
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data

volumes:
  redis:
    name: redis