version: '3.7'

services:
  web-transport:
    build:
      context: ./web/transport
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app
    volumes:
      - './web/transport:/usr/src/app'
    environment:
      PORT: 6001
    command: 'yarn start:dev'
    ports:
      - '6001:6001'

  web-deputies:
    build:
      context: ./web/deputies
      dockerfile: Dockerfile.dev
    volumes:
      - './web/deputies:/usr/src/app'
    environment:
      PORT: 6002
    command: 'yarn start:dev'
    ports:
      - '6002:6002'

  web-equipment:
    build:
      context: ./web/equipment
      dockerfile: Dockerfile.dev
    volumes:
      - './web/equipment:/usr/src/app'
    environment:
      PORT: 6003
    command: 'yarn start:dev'
    ports:
      - '6003:6003'

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.dev
    hostname: api
    depends_on: 
      - redis
    volumes:
      - './services/api:/usr/src/app'
    environment:
      PORT: 8080
    command: 'yarn start:dev'
    ports:
      - '8080:8080'

  watcher:
    build:
      context: ./services/watcher
      dockerfile: Dockerfile.dev
    hostname: watcher
    depends_on: 
      - api
      - mongo
      - redis
    volumes:
      - './services/watcher:/usr/src/app'
    environment:
      PORT: 8081
    command: 'yarn start:dev'
    ports:
      - '8081:8081'

  redis:
    build:
      context: ./services/redis
      dockerfile: Dockerfile.dev
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  mongo:
    build:
      context: ./services/mongo
      dockerfile: Dockerfile.dev
    container_name: mongo
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  redis:
    name: redis
  mongo:
    name: mongo