version: '3.7'

services:

  entry:
    image: ghcr.io/husky-dev/kremen-api/entry:latest
    build:
      context: ./services/entry
      dockerfile: Dockerfile

  api:
    image: ghcr.io/husky-dev/kremen-api/api:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile.prd
  
  watchman:
    image: ghcr.io/husky-dev/kremen-api/watchman:latest
    build:
      context: ./services/watchman
      dockerfile: Dockerfile.prd

  redis:
    image: ghcr.io/husky-dev/kremen-api/redis:latest
    build:
      context: ./services/redis
      dockerfile: Dockerfile.prd

  mongo:
    image: ghcr.io/husky-dev/kremen-api/mongo:latest
    build:
      context: ./services/mongo
      dockerfile: Dockerfile.prd

  backup:
    image: ghcr.io/husky-dev/kremen-api/backup:latest
    build:
      context: ./services/backup
      dockerfile: Dockerfile.prd
