version: "3.7"

services:

  entry:
    image: docker.pkg.github.com/husky-dev/kremen-api/entry:latest
    container_name: entry
    hostname: entry
    depends_on:
      - api
    volumes:
      - './creds/ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  wss:
    image: docker.pkg.github.com/husky-dev/kremen-api/wss:latest
    container_name: wss
    hostname: wss
    depends_on:
      - api
    restart: always

  api:
    image: docker.pkg.github.com/husky-dev/kremen-api/api:latest
    container_name: api
    hostname: api
    restart: always
