version: '3.7'

services:

  nginx:
    image: ghcr.io/husky-dev/kremen-api/nginx:latest
    build:
      context: ./services/nginx

  transport-api:
    image: ghcr.io/husky-dev/kremen-api/transport-api:latest
    build:
      context: ./services/transport

  equipment-api:
    image: ghcr.io/husky-dev/kremen-api/equipment-api:latest
    build:
      context: ./services/equipment
  
  watchman:
    image: ghcr.io/husky-dev/kremen-api/watchman:latest
    build:
      context: ./services/watchman

  backup:
    image: ghcr.io/husky-dev/kremen-api/backup:latest
    build:
      context: ./services/backup
