version: '3.7'

services:

  entry:
    image: docker.pkg.github.com/husky-dev/kremen-api/entry:latest
    container_name: entry
    hostname: entry
    depends_on:
      - api
    volumes:
      - './creds/ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  watcher:
    image: docker.pkg.github.com/husky-dev/kremen-api/watcher:latest
    container_name: watcher
    hostname: watcher
    depends_on:
      - api
      - mongo
      - redis
    restart: always

  api:
    image: docker.pkg.github.com/husky-dev/kremen-api/api:latest
    container_name: api
    hostname: api
    depends_on: 
      - redis
    restart: always

  redis:
    image: docker.pkg.github.com/husky-dev/kremen-api/redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data
    restart: alwasy

  mongo:
    image: docker.pkg.github.com/husky-dev/kremen-api/mongo:latest
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart: alwasy

volumes:
  redis:
    name: redis
  mongo:
    name: mongo
