version: '3.7'

services:

  nginx:
    build:
      context: ./services/nginx
    container_name: nginx
    hostname: nginx
    depends_on:
      - transport-api
      - equipment-api
      - cinemas-api
      - ws
      - redis
    volumes:
      - ./services/nginx/conf/dev:/etc/nginx/conf.d
    ports:
      - '80:80'

  transport-api:
    image: node:18-alpine3.16
    container_name: transport-api
    hostname: transport-api
    working_dir: '/srv'
    volumes:
      - './services/transport-api:/srv'
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=dev
      - LOG_LEVEL=debug
      - SENTRY_DSN=$TRANSPORT_API_SENTRY_DSN
    ports:
      - '8081:8080'
    command: 'yarn start:dev'

  equipment-api:
    image: node:17.4-alpine3.15
    container_name: equipment-api
    hostname: equipment-api
    working_dir: '/usr/src/app'
    volumes:
      - './services/equipment-api:/usr/src/app'
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=dev
      - LOG_LEVEL=debug
      - SENTRY_DSN=$EQUIPMENT_API_SENTRY_DSN
    ports:
      - '8082:8080'
    command: 'yarn start:dev'

  cinemas-api:
    image: node:17.4-alpine3.15
    container_name: cinemas-api
    hostname: cinemas-api
    working_dir: '/usr/src/app'
    volumes:
      - './services/cinemas-api:/usr/src/app'
    environment:
      - NODE_ENV=dev
      - LOG_LEVEL=debug
      - BOT_WEBHOOK=dev
      - BOT_TOKEN=$CINEMAS_BOT_TOKEN
      - SENTRY_DSN=$CINEMAS_API_SENTRY_DSN
    ports:
      - '8083:8080'
    command: 'yarn start:dev'

  img:
    build:
      context: ./services/img
      dockerfile: Dockerfile.dev
    container_name: img
    hostname: img
    working_dir: '/usr/src/app'
    volumes:
      - './services/img:/usr/src/app'
    environment:
      - NODE_ENV=dev
      - LOG_LEVEL=debug
      - CACHE_ENABLED=true
    ports:
      - '8084:8080'
    command: 'yarn start:dev'

  ws:
    image: node:17.4-alpine3.15
    container_name: ws
    hostname: ws
    working_dir: '/usr/src/app'
    volumes:
      - './services/ws:/usr/src/app'
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - SENTRY_DSN=$WATCHMAN_API_SENTRY_DSN
    command: 'yarn start:dev'

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  mongo:
    image: mongo:6.0.4
    container_name: mongo
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes:
  redis:
    name: kremen-api-redis
  mongo:
    name: kremen-api-mongo
