version: '3.7'

services:

  entry:
    image: docker.pkg.github.com/husky-dev/kremen-api/entry:latest
    container_name: entry
    hostname: entry
    depends_on:
      - api
    volumes:
      - 'ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  watchman:
    image: docker.pkg.github.com/husky-dev/kremen-api/watchman:latest
    container_name: watchman
    hostname: watchman
    depends_on:
      - api
      - mongo
      - redis
    restart: always

  api:
    image: docker.pkg.github.com/husky-dev/kremen-api/api:latest
    container_name: api
    hostname: api
    depends_on: 
      - redis
    restart: always

  slack:
    image: docker.pkg.github.com/husky-dev/kremen-api/slack:latest
    container_name: slack
    hostname: slack
    restart: always
    environment:
      - PORT=80
      - SLACK_URL=kremendev.slack.com
      - COMMUNITY_NAME=Kremen Dev Community
      - SLACK_TOKEN

  redis:
    image: docker.pkg.github.com/husky-dev/kremen-api/redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data
    restart: always

  mongo:
    image: docker.pkg.github.com/husky-dev/kremen-api/mongo:latest
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  ssl:
    name: ssl
  redis:
    name: redis
  mongo:
    name: mongo
