version: '3.7'

services:

  nginx:
    image: ghcr.io/husky-dev/kremen-api/nginx:latest
    container_name: nginx
    hostname: nginx
    depends_on:
      - transport-api
      - equipment-api
      - img
      - ws
    volumes:
      - 'ssl:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  transport-api:
    image: ghcr.io/husky-dev/kremen-api/transport-api:latest
    container_name: transport-api
    hostname: transport-api
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV
      - LOG_LEVEL
      - SENTRY_DSN=$TRANSPORT_API_SENTRY_DSN
    restart: always

  equipment-api:
    image: ghcr.io/husky-dev/kremen-api/equipment-api:latest
    container_name: equipment-api
    hostname: equipment-api
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV
      - LOG_LEVEL
      - SENTRY_DSN=$EQUIPMENT_API_SENTRY_DSN
    restart: always

  ws:
    image: ghcr.io/husky-dev/kremen-api/ws:latest
    container_name: ws
    hostname: ws
    depends_on:
      - redis
    environment:
      - NODE_ENV
      - LOG_LEVEL
      - SENTRY_DSN=$WS_SENTRY_DSN
    restart: always

  img:
    image: ghcr.io/husky-dev/kremen-api/img:latest
    container_name: img
    hostname: img
    volumes:
      - 'img-cache:/usr/src/app/cache'
    environment:
      - NODE_ENV
      - LOG_LEVEL
      - CACHE_ENABLED
    restart: always

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    volumes:
      - redis:/data
    restart: always

  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  ssl:
    name: ssl
  redis:
    name: redis
  mongo:
    name: mongo
  img-cache:
    name: img-cache
