version: "3.7"

services:
  web-dev:
    image: kremen-web-dev
    build:
      context: ./web/dev
      dockerfile: Dockerfile.build
  web-transport:
    image: kremen-web-transport
    build:
      context: ./web/transport
      dockerfile: Dockerfile.build
  entry:
    image: docker.pkg.github.com/husky-dev/kremen-api/entry:latest
    build:
      context: ./services/entry
      dockerfile: Dockerfile.build
  api:
    image: docker.pkg.github.com/husky-dev/kremen-api/api:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile.build
  wss:
    image: docker.pkg.github.com/husky-dev/kremen-api/wss:latest
    build:
      context: ./services/wss
      dockerfile: Dockerfile.build
  redis:
    image: docker.pkg.github.com/husky-dev/kremen-api/redis:latest
    build:
      context: ./services/redis
      dockerfile: Dockerfile.build
