service:
  name: kremen-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  transport:
    handler: handleTransport.handler
    events:
      - http:
          method: get
          path: transport/routes
      - http:
          method: get
          path: transport/buses
      - http:
          method: get
          path: transport/find
      - http:
          method: get
          path: transport/buses/short
      - http:
          method: get
          path: transport/stations
      - http:
          method: get
          path: transport/routes/{id}/buses
      - http:
          method: get
          path: transport/routes/{id}/stations
  cinemas:
    handler: handleCinemas.handler
    events:
      - http:
          method: get
          path: cinemas
