service:
  name: kremen-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 8
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    REDIS_HOST: ${file(config.${self:provider.stage}.json):REDIS_HOST}
    REDIS_PORT: ${file(config.${self:provider.stage}.json):REDIS_PORT}
    REDIS_PASS: ${file(config.${self:provider.stage}.json):REDIS_PASS}

functions:
  transport:
    handler: src/handlers/transport.handler
    events:
      - http:
          method: get
          path: transport/routes
          cors: true
      - http:
          method: get
          path: transport/buses
          cors: true
      - http:
          method: get
          path: transport/find
          cors: true
      - http:
          method: get
          path: transport/buses/update
          cors: true
      - http:
          method: get
          path: transport/stations
          cors: true
      - http:
          method: get
          path: transport/stations/{id}/prediction
          cors: true
      - http:
          method: get
          path: transport/routes/{id}/buses
          cors: true
      - http:
          method: get
          path: transport/routes/{id}/stations
          cors: true

  cinemas:
    handler: src/handlers/cinemas.handler
    events:
      - http:
          method: get
          path: cinemas
          cors: true
      - http:
          method: get
          path: cinemas/{cid}
          cors: true

  equipment:
    handler: src/handlers/equipment.handler
    events:
      - http:
          method: get
          path: equipment
          cors: true
