FROM node:17.4-alpine3.15

WORKDIR /usr/src/app

RUN apk add --no-cache \
  fontconfig \
  freetype \
  ttf-freefont \
  font-noto-emoji \
  font-vollkorn \
  font-misc-cyrillic \
  font-mutt-misc \
  font-screen-cyrillic \
  font-winitzki-cyrillic \
  font-cronyx-cyrillic
ENV FONTCONFIG_PATH=/usr/src/app/fonts
