name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: 'Env: set package version'
      run: >
        echo "VERSION=$(cat package.json | grep version | head -1 | awk
        -F: '{ print $2 }' | sed 's/[",\t ]//g')" >> $GITHUB_ENV
    - name: 'Docker: login'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: 'Docker: build'
      run: make build
    - name: 'Docker: push'
      run: make push
    - name: 'Telegram: done'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        args: |
          🏁 *kremen-api@${{ env.VERSION }}:* build finished
